import { BusinessType, Cuisine } from './types';

export const CUISINE_INGREDIENT_TERMS: Record<Cuisine, string[]> = {
  'South Indian': [
    'banana',
    'beans',
    'brinjal',
    'chilli',
    'coconut',
    'coriander',
    'curry leaf',
    'drumstick',
    'lemon',
    'okra',
    'onion',
    'spinach',
    'tomato',
  ],
  'North Indian': [
    'beetroot',
    'capsicum',
    'cauliflower',
    'chilli',
    'coriander',
    'fenugreek',
    'lemon',
    'mushroom',
    'onion',
    'peas',
    'potato',
    'spinach',
    'tomato',
  ],
  Chinese: [
    'bok choy',
    'broccoli',
    'cabbage',
    'capsicum',
    'carrot',
    'chilli',
    'mushroom',
    'onion',
    'scallion',
    'spring onion',
  ],
  Italian: [
    'arugula',
    'basil',
    'bell pepper',
    'cherry tomato',
    'mushroom',
    'parsley',
    'rocket',
    'spinach',
    'tomato',
    'zucchini',
  ],
  Continental: [
    'asparagus',
    'broccoli',
    'carrot',
    'herb',
    'lettuce',
    'mushroom',
    'potato',
    'salad',
    'spinach',
    'zucchini',
  ],
  American: [
    'avocado',
    'corn',
    'lettuce',
    'mushroom',
    'onion',
    'potato',
    'salad',
    'tomato',
  ],
  Mexican: [
    'avocado',
    'bell pepper',
    'chilli',
    'cilantro',
    'corn',
    'jalapeno',
    'lemon',
    'lime',
    'onion',
    'tomato',
  ],
  Japanese: [
    'daikon',
    'edamame',
    'mushroom',
    'radish',
    'scallion',
    'shiso',
    'spinach',
    'spring onion',
  ],
  'Pan Asian': [
    'bok choy',
    'broccoli',
    'cabbage',
    'chilli',
    'mushroom',
    'scallion',
    'spring onion',
    'thai basil',
  ],
  Bakery: [
    'apple',
    'banana',
    'berry',
    'lemon',
    'mint',
    'orange',
    'strawberry',
  ],
  'Multi Cuisine': [
    'carrot',
    'coriander',
    'leafy',
    'lemon',
    'mushroom',
    'onion',
    'potato',
    'tomato',
  ],
};

export const BUSINESS_INGREDIENT_TERMS: Record<BusinessType, string[]> = {
  Restaurant: ['herb', 'leafy', 'microgreen', 'mushroom', 'salad', 'specialty'],
  Café: ['avocado', 'berry', 'fruit', 'leafy', 'lettuce', 'microgreen', 'salad'],
  'Hotel & Resort': ['exotic', 'fruit', 'herb', 'leafy', 'microgreen', 'mushroom', 'salad'],
  'Cloud Kitchen': ['carrot', 'leafy', 'onion', 'potato', 'tomato', 'vegetable'],
  'Pub & Bar': ['citrus', 'fruit', 'lemon', 'lime', 'mint', 'mushroom'],
  Caterer: ['carrot', 'fruit', 'leafy', 'onion', 'potato', 'tomato', 'vegetable'],
  'Retail Store': ['fruit', 'leafy', 'mushroom', 'seasonal', 'vegetable'],
  'Event Organiser': ['exotic', 'fruit', 'microgreen', 'salad', 'specialty'],
};
